name = "actions"
main = "src/worker.js"
compatibility_date = "2024-11-15"
workers_dev = false
preview_urls = true

[[routes]]
pattern = "workers.tablerus.es/actions/*"
zone_name = "tablerus.es"

[placement]
mode = "smart"

[[kv_namespaces]]
id = "470b34600efb446da949928531359e2e"
binding = "ACTIONS_KV"

[[services]]
binding = "GOOGLEFORMS"
service = "googleforms"
environment = "production"
entrypoint = "ActionHandler"

[[services]]
binding = "UTILS"
service = "utils"
environment = "production"
entrypoint = "UtilsWorker"
